/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class VueLesVisiteurs extends javax.swing.JFrame {

    /**
     * Creates new form Visiteur
     */
    public VueLesVisiteurs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVisiteurs = new javax.swing.JLabel();
        jPanelVisiteur = new javax.swing.JPanel();
        jLabelVisiteurChercher = new javax.swing.JLabel();
        jSeparatorVisiteur = new javax.swing.JSeparator();
        jLabelVisiteurNom = new javax.swing.JLabel();
        jComboBoxVisiteurChercher = new javax.swing.JComboBox();
        jButtonVisiteurOk = new javax.swing.JButton();
        jTextFieldVisiteurNom = new javax.swing.JTextField();
        jLabelVisiteurPrenom = new javax.swing.JLabel();
        jTextFieldVisiteurPrenom = new javax.swing.JTextField();
        jLabelVisiteurAdresse = new javax.swing.JLabel();
        jLabelVisiteurVille = new javax.swing.JLabel();
        jLabelVisiteurSecteur = new javax.swing.JLabel();
        jTextFieldVisiteurAdresse = new javax.swing.JTextField();
        jTextFieldVisiteurCP = new javax.swing.JTextField();
        jTextFieldVisiteurVille = new javax.swing.JTextField();
        jComboBoxVisiteurSecteur = new javax.swing.JComboBox();
        jLabelVisiteurLabo = new javax.swing.JLabel();
        jComboBoxVisiteurLabo = new javax.swing.JComboBox();
        jButtonVisiteurPrecedent = new javax.swing.JButton();
        jButtonVisiteurSuivant = new javax.swing.JButton();
        jButtonVisiteurFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelVisiteurs.setFont(new java.awt.Font("GentiumAlt", 1, 48)); // NOI18N
        jLabelVisiteurs.setText("Visiteurs");

        jLabelVisiteurChercher.setText("Chercher");

        jLabelVisiteurNom.setText("NOM");

        jButtonVisiteurOk.setText("OK");

        jLabelVisiteurPrenom.setText("PRENOM");
        jLabelVisiteurPrenom.setToolTipText("");

        jLabelVisiteurAdresse.setText("ADRESSE");

        jLabelVisiteurVille.setText("VILLE");

        jLabelVisiteurSecteur.setText("SECTEUR");

        jComboBoxVisiteurSecteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelVisiteurLabo.setText("LABO");

        jComboBoxVisiteurLabo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonVisiteurPrecedent.setText("PRECEDENT");

        jButtonVisiteurSuivant.setText("SUIVANT");
        jButtonVisiteurSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisiteurSuivantActionPerformed(evt);
            }
        });

        jButtonVisiteurFermer.setText("FERMER");
        jButtonVisiteurFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisiteurFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVisiteurLayout = new javax.swing.GroupLayout(jPanelVisiteur);
        jPanelVisiteur.setLayout(jPanelVisiteurLayout);
        jPanelVisiteurLayout.setHorizontalGroup(
            jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisiteurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparatorVisiteur)
                    .addGroup(jPanelVisiteurLayout.createSequentialGroup()
                        .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVisiteurLayout.createSequentialGroup()
                                .addComponent(jLabelVisiteurChercher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxVisiteurChercher, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonVisiteurOk))
                            .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisiteurLayout.createSequentialGroup()
                                    .addComponent(jLabelVisiteurLabo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxVisiteurLabo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisiteurLayout.createSequentialGroup()
                                    .addComponent(jLabelVisiteurSecteur)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxVisiteurSecteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisiteurLayout.createSequentialGroup()
                                    .addComponent(jLabelVisiteurVille)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldVisiteurCP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldVisiteurVille))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisiteurLayout.createSequentialGroup()
                                    .addComponent(jLabelVisiteurAdresse)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldVisiteurAdresse))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisiteurLayout.createSequentialGroup()
                                    .addComponent(jLabelVisiteurPrenom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldVisiteurPrenom))
                                .addGroup(jPanelVisiteurLayout.createSequentialGroup()
                                    .addComponent(jLabelVisiteurNom)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldVisiteurNom, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelVisiteurLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonVisiteurPrecedent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVisiteurSuivant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jButtonVisiteurFermer)
                .addGap(44, 44, 44))
        );
        jPanelVisiteurLayout.setVerticalGroup(
            jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisiteurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurChercher)
                    .addComponent(jComboBoxVisiteurChercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVisiteurOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurNom)
                    .addComponent(jTextFieldVisiteurNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurPrenom)
                    .addComponent(jTextFieldVisiteurPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurAdresse)
                    .addComponent(jTextFieldVisiteurAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurVille)
                    .addComponent(jTextFieldVisiteurCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVisiteurVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurSecteur)
                    .addComponent(jComboBoxVisiteurSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisiteurLabo)
                    .addComponent(jComboBoxVisiteurLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelVisiteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVisiteurPrecedent)
                    .addComponent(jButtonVisiteurSuivant)
                    .addComponent(jButtonVisiteurFermer))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabelVisiteurs))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanelVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelVisiteurs)
                .addGap(18, 18, 18)
                .addComponent(jPanelVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisiteurSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisiteurSuivantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisiteurSuivantActionPerformed

    private void jButtonVisiteurFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisiteurFermerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisiteurFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueLesVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueLesVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueLesVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueLesVisiteurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueLesVisiteurs().setVisible(true);
            }
        });
    }

    public JButton getjButtonVisiteurFermer() {
        return jButtonVisiteurFermer;
    }

    public void setjButtonVisiteurFermer(JButton jButtonVisiteurFermer) {
        this.jButtonVisiteurFermer = jButtonVisiteurFermer;
    }

    public JButton getjButtonVisiteurOk() {
        return jButtonVisiteurOk;
    }

    public void setjButtonVisiteurOk(JButton jButtonVisiteurOk) {
        this.jButtonVisiteurOk = jButtonVisiteurOk;
    }

    public JButton getjButtonVisiteurPrecedent() {
        return jButtonVisiteurPrecedent;
    }

    public void setjButtonVisiteurPrecedent(JButton jButtonVisiteurPrecedent) {
        this.jButtonVisiteurPrecedent = jButtonVisiteurPrecedent;
    }

    public JButton getjButtonVisiteurSuivant() {
        return jButtonVisiteurSuivant;
    }

    public void setjButtonVisiteurSuivant(JButton jButtonVisiteurSuivant) {
        this.jButtonVisiteurSuivant = jButtonVisiteurSuivant;
    }

    public JComboBox getjComboBoxVisiteurChercher() {
        return jComboBoxVisiteurChercher;
    }

    public void setjComboBoxVisiteurChercher(JComboBox jComboBoxVisiteurChercher) {
        this.jComboBoxVisiteurChercher = jComboBoxVisiteurChercher;
    }

    public JComboBox getjComboBoxVisiteurLabo() {
        return jComboBoxVisiteurLabo;
    }

    public void setjComboBoxVisiteurLabo(JComboBox jComboBoxVisiteurLabo) {
        this.jComboBoxVisiteurLabo = jComboBoxVisiteurLabo;
    }

    public JComboBox getjComboBoxVisiteurSecteur() {
        return jComboBoxVisiteurSecteur;
    }

    public void setjComboBoxVisiteurSecteur(JComboBox jComboBoxVisiteurSecteur) {
        this.jComboBoxVisiteurSecteur = jComboBoxVisiteurSecteur;
    }

    public JTextField getjTextFieldVisiteurAdresse() {
        return jTextFieldVisiteurAdresse;
    }

    public void setjTextFieldVisiteurAdresse(JTextField jTextFieldVisiteurAdresse) {
        this.jTextFieldVisiteurAdresse = jTextFieldVisiteurAdresse;
    }

    public JTextField getjTextFieldVisiteurCP() {
        return jTextFieldVisiteurCP;
    }

    public void setjTextFieldVisiteurCP(JTextField jTextFieldVisiteurCP) {
        this.jTextFieldVisiteurCP = jTextFieldVisiteurCP;
    }

    public JTextField getjTextFieldVisiteurNom() {
        return jTextFieldVisiteurNom;
    }

    public void setjTextFieldVisiteurNom(JTextField jTextFieldVisiteurNom) {
        this.jTextFieldVisiteurNom = jTextFieldVisiteurNom;
    }

    public JTextField getjTextFieldVisiteurPrenom() {
        return jTextFieldVisiteurPrenom;
    }

    public void setjTextFieldVisiteurPrenom(JTextField jTextFieldVisiteurPrenom) {
        this.jTextFieldVisiteurPrenom = jTextFieldVisiteurPrenom;
    }

    public JTextField getjTextFieldVisiteurVille() {
        return jTextFieldVisiteurVille;
    }

    public void setjTextFieldVisiteurVille(JTextField jTextFieldVisiteurVille) {
        this.jTextFieldVisiteurVille = jTextFieldVisiteurVille;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVisiteurFermer;
    private javax.swing.JButton jButtonVisiteurOk;
    private javax.swing.JButton jButtonVisiteurPrecedent;
    private javax.swing.JButton jButtonVisiteurSuivant;
    private javax.swing.JComboBox jComboBoxVisiteurChercher;
    private javax.swing.JComboBox jComboBoxVisiteurLabo;
    private javax.swing.JComboBox jComboBoxVisiteurSecteur;
    private javax.swing.JLabel jLabelVisiteurAdresse;
    private javax.swing.JLabel jLabelVisiteurChercher;
    private javax.swing.JLabel jLabelVisiteurLabo;
    private javax.swing.JLabel jLabelVisiteurNom;
    private javax.swing.JLabel jLabelVisiteurPrenom;
    private javax.swing.JLabel jLabelVisiteurSecteur;
    private javax.swing.JLabel jLabelVisiteurVille;
    private javax.swing.JLabel jLabelVisiteurs;
    private javax.swing.JPanel jPanelVisiteur;
    private javax.swing.JSeparator jSeparatorVisiteur;
    private javax.swing.JTextField jTextFieldVisiteurAdresse;
    private javax.swing.JTextField jTextFieldVisiteurCP;
    private javax.swing.JTextField jTextFieldVisiteurNom;
    private javax.swing.JTextField jTextFieldVisiteurPrenom;
    private javax.swing.JTextField jTextFieldVisiteurVille;
    // End of variables declaration//GEN-END:variables
}
